ALTER TABLE consumidores ADD COLUMN ativo BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE produtores ADD COLUMN ativo BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE restaurantes ADD COLUMN ativo BOOLEAN NOT NULL DEFAULT TRUE;